export type Lang = 'en' | 'es';

const copy = {
  en: {
    tech: {
      top: 'Back to top',
      menuOpen: 'Open menu',
      menuClose: 'Close menu',
      redefined: 'PERFORMANCE TECHNOLOGY FOR COMBAT SPORTS',
      dual: 'DUAL SENSOR SETUP',
      athlete: 'ATHLETE',
      target: 'TARGET',
      live: 'EXAMPLE SESSION',
      measure: 'ENGINEERED TO MEASURE',
      standard: 'A NEW PERSPECTIVE ON COMBAT DATA',
      scroll: 'SCROLL TO EXPLORE',
      modular: 'MODULAR HARDWARE',
      core: 'SENSOR CORE',
      same: 'SAME HARDWARE',
      capture: 'CAPTURE',
      time: 'TIME',
      work: 'BUILT FOR THE WORK. NOT THE SPOTLIGHT.',
      system: 'SYSTEM',
      analysis: 'SESSION ANALYSIS',
      intelligence: 'PERFORMANCE INTELLIGENCE',
      early: 'EARLY ACCESS',
      concept: 'CONCEPT ILLUSTRATION',
      heroAlt: 'Athlete training a kick in a combat sports gym, with demonstration timing overlaid',
      sportsAlt: 'Athlete practicing a jumping strike in a combat sports gym',
      total: 'TOTAL RESPONSE',
      cycle: 'COMPLETE CYCLE',
      socialSoon: 'Social links coming soon',
      mounts: 'T0 mounting options',
    },
    nav: ['Product', 'How it works', 'For coaches', 'Waitlist'],
    join: 'Join waitlist',
    coming: 'Coming 2027',
    heroTitle: "A FAST KICK ISN'T ONE NUMBER.",
    heroBody:
      'Reaction. Execution. Impact. Recovery. SIJAK turns a combat-sport action into a measurable timeline.',
    seeHow: 'See a measurement',
    heroNote: 'ONE ACTION. THE WHOLE STORY.',
    conceptEyebrow: '01 / THE HARDWARE',
    conceptTitle: 'ONE SENSOR. MULTIPLE ROLES.',
    conceptBody:
      'Built to move with you. The same T0 clicks into different mounts, adapting to your training instead of the other way around.',
    mounts: [
      ['ANKLE', 'KICK'],
      ['WRIST', 'PUNCH'],
      ['PADDLE', 'TARGET'],
      ['SHIELD', 'IMPACT'],
      ['BODY', 'MOVEMENT'],
    ],
    sensorLabel: 'THE SAME T0. A DIFFERENT PERSPECTIVE.',
    workEyebrow: '02 / THE METHOD',
    workTitle: 'ONE ACTION. THE WHOLE STORY.',
    workBody:
      'SIJAK splits a combat-sport action into moments you can measure, compare and follow over time.',
    timeline: ['STIMULUS', 'REACTION', 'MOVEMENT', 'EXECUTION', 'IMPACT', 'RECOVERY'],
    athlete: 'ATHLETE SENSOR',
    target: 'TARGET SENSOR',
    shared: 'ONE SHARED TIMELINE',
    metricsEyebrow: '03 / THE DATA',
    metricsTitle: 'TURN MOVEMENT INTO DATA.',
    metricsBody:
      'Not just how hard you hit. How quickly you started, how efficiently you moved, and how ready you were to go again.',
    metrics: ['REACTION', 'EXECUTION', 'RECOVERY', 'CONSISTENCY', 'PEAK ACCELERATION'],
    example: 'ILLUSTRATIVE SESSION DATA',
    sportsEyebrow: '04 / THE ARENA',
    sportsTitle: 'BUILT FOR COMBAT SPORTS.',
    sportsBody: 'Different disciplines. The same drive to get better.',
    sports: ['TAEKWON-DO', 'BOXING', 'KICKBOXING', 'MUAY THAI', 'KARATE', 'MMA'],
    systemEyebrow: '05 / THE SYSTEM',
    systemTitle: 'START WITH ONE. BUILD YOUR SYSTEM.',
    systemBody: 'One sensor remains useful. Two unlock the complete athlete-to-target timeline.',
    solo: 'For individual training',
    duo: 'Athlete + target',
    duoExtra: 'Full action analysis',
    team: 'For coaches and clubs',
    sensors: 'sensors',
    sensor: 'sensor',
    early: 'Join early access',
    coachEyebrow: '06 / FOR COACHES',
    coachTitle: "SEE WHAT THE EYE CAN'T MEASURE.",
    coachBody: 'A coach can see a fast kick. T0 helps measure where the time is being lost.',
    left: 'LEFT LEG',
    right: 'RIGHT LEG',
    insight: 'Recovery is 24% slower on the left side.',
    insightLabel: 'THE INSIGHT',
    waitEyebrow: 'YOUR NEXT ROUND STARTS HERE',
    waitTitle: 'BE ONE OF THE FIRST TO TRAIN WITH T0.',
    waitBody: 'Join the waitlist for early access, pilot testing opportunities and launch pricing.',
    name: 'Name',
    email: 'Email',
    country: 'Country',
    sport: 'Sport',
    role: 'I am a',
    roles: ['Athlete', 'Coach', 'Club'],
    count: 'How many athletes do you train? (optional)',
    select: 'Select an option',
    submit: 'Join the waitlist',
    sending: 'Joining...',
    success: "YOU'RE IN.",
    successBody: 'Everyone starts here.',
    formError: 'Something went wrong. Please try again later.',
    errors: {
      title: 'REVIEW THESE DETAILS',
      network: 'No connection. Check your network and try again.',
      unavailable: 'We could not save this. Your details are still here — try again.',
      invalid: 'Some details are not valid. Review the highlighted fields.',
      unexpected: 'Something went wrong. Please try again.',
      tooLarge: 'That request is too large. Shorten it and try again.',
      fields: {
        name: 'Enter your name (up to 100 characters, without line breaks).',
        email: 'Enter a valid email address.',
        country: 'Enter your country.',
        sport: 'Select a sport.',
        role: 'Choose athlete, coach or club.',
        consent: 'Accept the privacy note to continue.',
        athleteCount: 'Use a whole number up to 100000, or leave it empty.',
        message: 'Write a message of at least 5 characters.',
        lang: 'The language could not be confirmed. Reload the page and try again.',
      },
    },
    privacyNote: 'By joining, you agree to receive occasional updates about T0. No spam.',
    footerTag: 'Everyone starts here.',
    designed: 'Designed in Chile.',
    contact: 'Contact',
    contactTitle: 'LET’S TALK.',
    contactIntro: 'Questions about T0, partnerships, or requests to access and delete your data.',
    contactMessage: 'Message or privacy request',
    contactConsent: 'I agree to SIJAK using these details to handle my request.',
    contactSubmit: 'Send message',
    contactSending: 'Sending...',
    contactSuccessTitle: 'MESSAGE RECEIVED.',
    contactSuccessBody: 'Your message has been saved for the SIJAK team to review.',
    privacy: 'Privacy',
    privacyTitle: 'PRIVACY',
    privacyBody:
      'SIJAK collects the name, email, country, sport, role and optional athlete count you submit to manage early access, pilot opportunities and launch updates. Your details are stored in private Vercel Blob storage and are not publicly accessible. We do not sell your data or use advertising trackers on this site. Participation is optional. You may request access, correction, removal or withdrawal of consent at any time using the contact form below. Contact messages are stored privately so our team can process your request.',
    back: 'Back to SIJAK',
    photo: 'Training imagery: Pexels.',
  },
  es: {
    tech: {
      top: 'Volver arriba',
      menuOpen: 'Abrir menú',
      menuClose: 'Cerrar menú',
      redefined: 'TECNOLOGÍA DE RENDIMIENTO PARA DEPORTES DE COMBATE',
      dual: 'SISTEMA DE DOS SENSORES',
      athlete: 'ATLETA',
      target: 'OBJETIVO',
      live: 'SESIÓN DE EJEMPLO',
      measure: 'DISEÑADO PARA MEDIR',
      standard: 'OTRA PERSPECTIVA DEL RENDIMIENTO',
      scroll: 'DESLIZA PARA EXPLORAR',
      modular: 'HARDWARE MODULAR',
      core: 'NÚCLEO DEL SENSOR',
      same: 'EL MISMO HARDWARE',
      capture: 'CAPTURA',
      time: 'TIEMPO',
      work: 'PARA ENTRENAR. NO PARA APARENTAR.',
      system: 'SISTEMA',
      analysis: 'ANÁLISIS DE SESIÓN',
      intelligence: 'INTELIGENCIA DE RENDIMIENTO',
      early: 'ACCESO ANTICIPADO',
      concept: 'ILUSTRACIÓN CONCEPTUAL',
      heroAlt:
        'Atleta entrenando una patada en un gimnasio de combate, con tiempos de demostración superpuestos',
      sportsAlt: 'Atleta practicando un golpe en salto en un gimnasio de combate',
      total: 'RESPUESTA TOTAL',
      cycle: 'CICLO COMPLETO',
      socialSoon: 'Enlaces sociales próximamente',
      mounts: 'Opciones de montaje de T0',
    },
    nav: ['Producto', 'Cómo funciona', 'Para entrenadores', 'Lista de espera'],
    join: 'Unirme a la lista',
    coming: 'Llega en 2027',
    heroTitle: 'UNA PATADA RÁPIDA NO ES UN SOLO NÚMERO.',
    heroBody:
      'Reacción. Ejecución. Impacto. Recuperación. SIJAK convierte una acción de combate en una línea de tiempo medible.',
    seeHow: 'Ver una medición',
    heroNote: 'UNA ACCIÓN. LA HISTORIA COMPLETA.',
    conceptEyebrow: '01 / EL HARDWARE',
    conceptTitle: 'UN SENSOR. MÚLTIPLES ROLES.',
    conceptBody:
      'Diseñado para moverse contigo. El mismo T0 encaja en distintos soportes y se adapta a tu entrenamiento, no al revés.',
    mounts: [
      ['TOBILLO', 'PATADA'],
      ['MUÑECA', 'GOLPE'],
      ['PALETA', 'OBJETIVO'],
      ['ESCUDO', 'IMPACTO'],
      ['CUERPO', 'MOVIMIENTO'],
    ],
    sensorLabel: 'EL MISMO T0. OTRA PERSPECTIVA.',
    workEyebrow: '02 / EL MÉTODO',
    workTitle: 'UNA ACCIÓN. TODA LA HISTORIA.',
    workBody:
      'SIJAK divide una acción de combate en momentos que puedes medir, comparar y seguir en el tiempo.',
    timeline: ['ESTÍMULO', 'REACCIÓN', 'MOVIMIENTO', 'EJECUCIÓN', 'IMPACTO', 'RECUPERACIÓN'],
    athlete: 'SENSOR DEL ATLETA',
    target: 'SENSOR DEL OBJETIVO',
    shared: 'UNA LÍNEA DE TIEMPO',
    metricsEyebrow: '03 / LOS DATOS',
    metricsTitle: 'CONVIERTE EL MOVIMIENTO EN DATOS.',
    metricsBody:
      'No solo cuánto impactas. Cuándo empezaste, cómo te moviste y en cuánto tiempo estuviste listo para volver.',
    metrics: ['REACCIÓN', 'EJECUCIÓN', 'RECUPERACIÓN', 'CONSISTENCIA', 'ACELERACIÓN MÁXIMA'],
    example: 'DATOS ILUSTRATIVOS DE UNA SESIÓN',
    sportsEyebrow: '04 / EL TERRENO',
    sportsTitle: 'HECHO PARA DEPORTES DE COMBATE.',
    sportsBody: 'Distintas disciplinas. Las mismas ganas de mejorar.',
    sports: ['TAEKWON-DO', 'BOXEO', 'KICKBOXING', 'MUAY THAI', 'KARATE', 'MMA'],
    systemEyebrow: '05 / EL SISTEMA',
    systemTitle: 'EMPIEZA CON UNO. CONSTRUYE TU SISTEMA.',
    systemBody:
      'Un sensor sigue siendo útil. Dos desbloquean la línea completa entre atleta y objetivo.',
    solo: 'Para entrenamiento individual',
    duo: 'Atleta + objetivo',
    duoExtra: 'Análisis completo de la acción',
    team: 'Para entrenadores y clubes',
    sensors: 'sensores',
    sensor: 'sensor',
    early: 'Solicitar acceso anticipado',
    coachEyebrow: '06 / PARA ENTRENADORES',
    coachTitle: 'VE LO QUE EL OJO NO PUEDE MEDIR.',
    coachBody:
      'Un entrenador puede ver una patada rápida. T0 ayuda a medir dónde se está perdiendo el tiempo.',
    left: 'PIERNA IZQUIERDA',
    right: 'PIERNA DERECHA',
    insight: 'La recuperación es un 24 % más lenta en el lado izquierdo.',
    insightLabel: 'EL HALLAZGO',
    waitEyebrow: 'TU PRÓXIMO ASALTO EMPIEZA AQUÍ',
    waitTitle: 'SÉ DE LOS PRIMEROS EN ENTRENAR CON T0.',
    waitBody:
      'Únete a la lista de espera para acceder antes, participar en pruebas piloto y conocer el precio de lanzamiento.',
    name: 'Nombre',
    email: 'Correo electrónico',
    country: 'País',
    sport: 'Deporte',
    role: 'Soy',
    roles: ['Atleta', 'Entrenador/a', 'Club'],
    count: '¿A cuántos atletas entrenas? (opcional)',
    select: 'Selecciona una opción',
    submit: 'Unirme a la lista',
    sending: 'Enviando...',
    success: 'YA ESTÁS DENTRO.',
    successBody: 'Todos empezamos aquí.',
    formError: 'Algo salió mal. Inténtalo de nuevo más tarde.',
    errors: {
      title: 'REVISA ESTOS DATOS',
      network: 'Sin conexión. Revisa tu red e inténtalo de nuevo.',
      unavailable: 'No pudimos guardar esto. Tus datos siguen aquí: inténtalo otra vez.',
      invalid: 'Hay datos que no son válidos. Revisa los campos marcados.',
      unexpected: 'Algo salió mal. Inténtalo de nuevo.',
      tooLarge: 'La solicitud es demasiado grande. Acórtala e inténtalo de nuevo.',
      fields: {
        name: 'Escribe tu nombre (máximo 100 caracteres, sin saltos de línea).',
        email: 'Escribe un correo electrónico válido.',
        country: 'Escribe tu país.',
        sport: 'Elige un deporte.',
        role: 'Indica si eres atleta, entrenador/a o club.',
        consent: 'Debes aceptar la nota de privacidad para continuar.',
        athleteCount: 'Usa un número entero hasta 100000, o déjalo vacío.',
        message: 'Escribe un mensaje de al menos 5 caracteres.',
        lang: 'No se pudo confirmar el idioma. Recarga la página e inténtalo de nuevo.',
      },
    },
    privacyNote: 'Al unirte, aceptas recibir novedades ocasionales sobre T0. Sin spam.',
    footerTag: 'Todos empezamos aquí.',
    designed: 'Diseñado en Chile.',
    contact: 'Contacto',
    contactTitle: 'HABLEMOS.',
    contactIntro:
      'Consultas sobre T0, colaboración o solicitudes de acceso y eliminación de datos.',
    contactMessage: 'Mensaje o solicitud de privacidad',
    contactConsent: 'Acepto que SIJAK utilice estos datos para gestionar mi consulta.',
    contactSubmit: 'Enviar mensaje',
    contactSending: 'Enviando...',
    contactSuccessTitle: 'MENSAJE RECIBIDO.',
    contactSuccessBody: 'Tu mensaje quedó registrado para revisión del equipo SIJAK.',
    privacy: 'Privacidad',
    privacyTitle: 'PRIVACIDAD',
    privacyBody:
      'SIJAK recopila el nombre, correo, país, deporte, rol y número opcional de atletas que envías para gestionar el acceso anticipado, las pruebas piloto y las novedades del lanzamiento. Tus datos se guardan en almacenamiento privado de Vercel Blob y no son públicos. No vendemos tus datos ni usamos rastreadores publicitarios en este sitio. Participar es voluntario. Puedes solicitar acceso, rectificación, eliminación o retirar tu consentimiento en cualquier momento mediante el formulario de contacto. Los mensajes también se guardan de forma privada para que el equipo gestione tu solicitud.',
    back: 'Volver a SIJAK',
    photo: 'Fotografías de entrenamiento: Pexels.',
  },
} as const;

export function getCopy(lang: Lang) {
  return copy[lang];
}
export type Copy = ReturnType<typeof getCopy>;
